name: syncchain
description: TIKI's local chain backup/sync (aka sync chain)
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/syncchain
issue_tracker: https://github.com/tiki/syncchain/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  sqflite_sqlcipher: ^2.1.0
  collection: ^1.15.0
  xml: ^5.3.1
  uuid: 3.0.5
  httpp:
    git:
      url: https://github.com/tiki/httpp
      ref: 0.0.3
  tiki_kv:
    git:
      url: https://github.com/tiki/tiki_kv
      ref: 0.1.0

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter
