name: syncchain
description: TIKI's local chain backup/sync (aka sync chain)
version: 0.0.1
homepage: https://mytiki.com
repository: https://github.com/tiki/syncchain
issue_tracker: https://github.com/tiki/syncchain/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  sqflite_sqlcipher: ^2.1.0

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #assets:
    #- packages/syncchain/src/db/sql/db_sql_create.sql
