name: tiki_syncchain
description: TIKI's local chain backup/sync (aka sync chain)
version: 0.0.10
homepage: https://mytiki.com
repository: https://github.com/tiki/syncchain
issue_tracker: https://github.com/tiki/syncchain/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  amplitude_flutter: ^3.10.0
  crypto: ^3.0.2
  http: ^0.13.4
  logging: ^1.0.2
  sqflite_sqlcipher: ^2.1.1
  collection: ^1.16.0
  xml: ^6.1.0
  uuid: ^3.0.6
  httpp: ^0.0.6
  tiki_kv: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
